apps:
  "104cac-apps": "資訊服務事業體-工程總處-互動工程處-新媒體開發部"
  "104jbc-apps": "資訊服務事業體-工程總處-職涯工程處-求職工程部"
  "104se-apps": "資訊服務事業體-系統服務處-平台服務部-平台維運課"
  "104vip-apps": "資訊服務事業體-工程總處-職涯工程處-求才工程部"
  "104isgd-devops-gitops-apps": "資訊服務事業體-整合服務處-技術發展部"
  "k8s-104dtt-apps": "資訊服務事業體-工程總處-研發處-研發工程部"
  "k8s-104fp-app": "資訊服務事業體-工程總處-互動工程處-平台工程部"
  "k8s-104mis-apps": "資訊服務事業體-工程總處-互動工程處-管理資訊部"
  "k8s-aiteam-apps": "資訊服務事業體-工程總處-職涯工程處-求職工程部"
  "k8s-infra-apps": "資訊服務事業體-整合服務處-技術策略部"